project_name: 'Bias Demo'
# modelling data
filename: 'data/DR_Demo_LendingClub_Guardrails_Fairness.csv.zip'
# modelling target
target: 'is_bad'
# value of favourable outcome
preferable_outcome: 'No'
# fairness metric for DataRobot UI
# One of proportionalParity, equalParity, predictionBalance, trueFavorableAndUnfavorableRateParity or FavorableAndUnfavorablePredictiveValueParity
fairness_metric: 'predictionBalance'
# protected features
protected: ['gender', 'race']
# profit values corresponding to quadrants of confusion matrix
tp_value: 0       # no bad loan, no loss
tn_value: 1500    # good loan written, $1500 profit made
fp_value: 0       # no good loan written, opportunity cost $1500 in profit, but net payoff is zero
fn_value: -10000  # bad loan written, $10000 in loan write-offs
